package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.16
 * 2018-07-23T14:32:11.909+08:00
 * Generated source version: 3.0.16
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ItemInfoServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ItemInfoServiceSoap {

    /**
     * 获取培训记录试卷信息
     */
    @WebResult(name = "GetRecordExamPageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRecordExamPage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecordExamPage")
    @WebMethod(operationName = "GetRecordExamPage", action = "http://tempuri.org/GetRecordExamPage")
    @ResponseWrapper(localName = "GetRecordExamPageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecordExamPageResponse")
    public org.tempuri.RecordExamList getRecordExamPage(
        @WebParam(name = "queryParams", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfDictionaryEntry queryParams,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page,
        @WebParam(name = "resultsPerpage", targetNamespace = "http://tempuri.org/")
        int resultsPerpage
    );

    /**
     * 获取培训记录人员培训信息
     */
    @WebResult(name = "GetRecordPersonPageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRecordPersonPage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecordPersonPage")
    @WebMethod(operationName = "GetRecordPersonPage", action = "http://tempuri.org/GetRecordPersonPage")
    @ResponseWrapper(localName = "GetRecordPersonPageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecordPersonPageResponse")
    public org.tempuri.RecordPersonList getRecordPersonPage(
        @WebParam(name = "queryParams", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfDictionaryEntry queryParams,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page,
        @WebParam(name = "resultsPerpage", targetNamespace = "http://tempuri.org/")
        int resultsPerpage
    );

    /**
     * 获取人员照片
     */
    @WebResult(name = "GetPersonPictureResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonPicture", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonPicture")
    @WebMethod(operationName = "GetPersonPicture", action = "http://tempuri.org/GetPersonPicture")
    @ResponseWrapper(localName = "GetPersonPictureResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonPictureResponse")
    public byte[] getPersonPicture(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        java.lang.String id
    );

    /**
     * 获取培训记录信息
     */
    @WebResult(name = "GetRecordPageResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRecordPage", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecordPage")
    @WebMethod(operationName = "GetRecordPage", action = "http://tempuri.org/GetRecordPage")
    @ResponseWrapper(localName = "GetRecordPageResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecordPageResponse")
    public org.tempuri.RecordList getRecordPage(
        @WebParam(name = "queryParams", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfDictionaryEntry queryParams,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page,
        @WebParam(name = "resultsPerpage", targetNamespace = "http://tempuri.org/")
        int resultsPerpage
    );

    /**
     * 测试方法
     */
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    public java.lang.String helloWorld();

    /**
     * 获取项目部用户
     */
    @WebResult(name = "GetRootProjectUsersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRootProjectUsers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRootProjectUsers")
    @WebMethod(operationName = "GetRootProjectUsers", action = "http://tempuri.org/GetRootProjectUsers")
    @ResponseWrapper(localName = "GetRootProjectUsersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRootProjectUsersResponse")
    public org.tempuri.ArrayOfUser getRootProjectUsers(
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    /**
     * 获取单位信息
     */
    @WebResult(name = "GetDepartResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDepart", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDepart")
    @WebMethod(operationName = "GetDepart", action = "http://tempuri.org/GetDepart")
    @ResponseWrapper(localName = "GetDepartResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDepartResponse")
    public org.tempuri.Depart getDepart(
        @WebParam(name = "Id", targetNamespace = "http://tempuri.org/")
        java.lang.String id
    );

    /**
     * 获取人员信息
     */
    @WebResult(name = "GetPersonsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersons", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersons")
    @WebMethod(operationName = "GetPersons", action = "http://tempuri.org/GetPersons")
    @ResponseWrapper(localName = "GetPersonsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonsResponse")
    public org.tempuri.PersonList getPersons(
        @WebParam(name = "queryParams", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfDictionaryEntry queryParams,
        @WebParam(name = "page", targetNamespace = "http://tempuri.org/")
        int page,
        @WebParam(name = "resultsPerpage", targetNamespace = "http://tempuri.org/")
        int resultsPerpage
    );

    /**
     * 根据人员身份证号获取培训项目
     */
    @WebResult(name = "GetPersonRecordByIdentiyIdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPersonRecordByIdentiyId", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonRecordByIdentiyId")
    @WebMethod(operationName = "GetPersonRecordByIdentiyId", action = "http://tempuri.org/GetPersonRecordByIdentiyId")
    @ResponseWrapper(localName = "GetPersonRecordByIdentiyIdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonRecordByIdentiyIdResponse")
    public org.tempuri.ArrayOfPersonRecord getPersonRecordByIdentiyId(
        @WebParam(name = "IdentifyID", targetNamespace = "http://tempuri.org/")
        java.lang.String identifyID
    );

    /**
     * 获取所有单位信息(项目部以下)
     */
    @WebResult(name = "GetDepartsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDeparts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeparts")
    @WebMethod(operationName = "GetDeparts", action = "http://tempuri.org/GetDeparts")
    @ResponseWrapper(localName = "GetDepartsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDepartsResponse")
    public org.tempuri.ArrayOfDepart getDeparts();

    /**
     * 获取所有单位信息(项目维度)
     */
    @WebResult(name = "GetItemDepartsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItemDeparts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetItemDeparts")
    @WebMethod(operationName = "GetItemDeparts", action = "http://tempuri.org/GetItemDeparts")
    @ResponseWrapper(localName = "GetItemDepartsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetItemDepartsResponse")
    public org.tempuri.ArrayOfDepart getItemDeparts();

    /**
     * 根据KindName获取编码信息
     */
    @WebResult(name = "GetCodeContentByKindNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCodeContentByKindName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCodeContentByKindName")
    @WebMethod(operationName = "GetCodeContentByKindName", action = "http://tempuri.org/GetCodeContentByKindName")
    @ResponseWrapper(localName = "GetCodeContentByKindNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCodeContentByKindNameResponse")
    public org.tempuri.ArrayOfCodeContent getCodeContentByKindName(
        @WebParam(name = "KindName", targetNamespace = "http://tempuri.org/")
        java.lang.String kindName
    );

    /**
     * 根据父级Id获取下级工具箱单位
     */
    @WebResult(name = "GetChildByParentIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetChildByParentID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChildByParentID")
    @WebMethod(operationName = "GetChildByParentID", action = "http://tempuri.org/GetChildByParentID")
    @ResponseWrapper(localName = "GetChildByParentIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetChildByParentIDResponse")
    public org.tempuri.ArrayOfProjectDepart getChildByParentID(
        @WebParam(name = "ParentID", targetNamespace = "http://tempuri.org/")
        java.lang.String parentID
    );

    /**
     * 获取项目部列表
     */
    @WebResult(name = "GetRootProjectResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRootProject", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRootProject")
    @WebMethod(operationName = "GetRootProject", action = "http://tempuri.org/GetRootProject")
    @ResponseWrapper(localName = "GetRootProjectResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRootProjectResponse")
    public org.tempuri.ArrayOfDepart getRootProject();
}
